### ISSUE TITLE
Fix issue with owners not allowed to edit sandbox objects they own

### ISSUE THREAD

**Issue by dvanbrocklin** [plexsystems/sandbox-operator#3]
Hi John,

We spoke about this in chat already, so I won't bother framing this too much.  We basically need this result:

- users listed as `owners` of a `Sandbox` should be able to edit/delete those specific objects
- users NOT listed as `owners` should NOT be able to edit/delete those specific objects

Looks like the `sandbox-*-deleter` cluster role is set up to do a similar sort of thing that we need, only it is limited to the "delete" verb.  We're looking for the "patch" verb for the exact same object.  The `sandbox-*-owner` role is namespaced, however, so we can't add it there.

Ideally, the `deleter` role would be `admin` allowing multiple verbs like "patch" and "delete".  However, renaming child object patterns can get sticky with in-place upgrades, so a workaround could be to just add the "patch" verb to the existing `deleter` cluster role.

What do you think, John?

**Comment by jpreese** [comment]
@dvanbrocklin makes sense to me!

**Cleanup Tasks**
- [x] Rename the sandbox-users ClusterRole to sandbox-user
- [x] Rename the sandbox-user ClusterRoleBinding to sandbox-users

**Enhancement Tasks**
- [x] Rename the sandbox-[name]-deleter ClusterRole to sandbox-[name]-admin
- [x] Rename the sandbox-[name]-deleters ClusterRoleBinding to sandbox-[name]-admins
- [x] Add the `update` verb to the sandbox-[name]-admin ClusterRole

**Comment by jpreese** [comment]
Resolved via #4
