### ISSUE TITLE
Secrets Management

### ISSUE THREAD

**Issue by ssmiller25** [plexsystems/sandbox-operator#5]
Noticed recently that sandbox users cannot [create secrets in their Sandbox namespace](https://github.com/plexsystems/sandbox-operator/blob/90e7ab71a6d9efb41cde668c656510bd38b24603/controller/sandbox.go#L257-L266), which may promote non-ideal configuration of not leveraging secrets in a deployment.  Although I'm not sure how to reconcile that permission along with anyone using [custom pullsecrets](https://github.com/plexsystems/sandbox-operator#docker-pull-secrets) that are copied to a namespace, with the presumption that you may not want those credentials given to the sandbox user directly.

**Comment by jpreese** [comment]
Unless it's a bug, owners should be able to create secrets. The policy you linked is `*` which is _all_ verbs. There's a section that just includes `create` and `secrets`

https://github.com/plexsystems/sandbox-operator/blob/90e7ab71a6d9efb41cde668c656510bd38b24603/controller/sandbox.go#L307

**Comment by ssmiller25** [comment]
Oh yea, completely missed that section.  What are your thoughts on adding the delete and list verb to secrets, so that an end-user would have a little more ability to managed secrets, but still coudn't pull back actual secret data?

**Comment by jpreese** [comment]
the list permission also includes get, so they would still be able to get the secrets back from the API. I don't really have a problem with deleting

**Comment by ssmiller25** [comment]
Oh yea...REST semantics and all (I presume).  Yea, I'll do a quick PR to add delete.

**Comment by jpreese** [comment]
Thanks for the PR! Resolved via #6
